/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hotlinecesena;

import org.junit.jupiter.api.Test;

import hotlinecesena.controller.GameController;

import static org.junit.jupiter.api.Assertions.*;

class GameControllerTest {
    @Test
    void appHasAGreeting() {
        GameController classUnderTest = new GameController();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
