/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hotlinecesena;

class GameControllerTest {
	/*
    @Test
    void appHasAGreeting() {
        GameController classUnderTest = new GameController();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    */
}
