/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.8.3/userguide/building_java_projects.html
 */

plugins {
    application
    eclipse
}

repositories {
    jcenter()
    mavenCentral()
    
    // jMonkeyEngine artifacts on Bintray
    maven {
        url = uri("https://dl.bintray.com/jmonkeyengine/org.jmonkeyengine")
    }
}

dependencies {
    // Use JUnit Jupiter API for testing.
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.7.1")

    // Use JUnit Jupiter Engine for testing.
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine")

    implementation("com.google.guava:guava:29.0-jre")
    
    // jMonkeyEngine artifacts
    compileOnly("org.jmonkeyengine:jme3-core:3.3.2-stable")
	runtimeOnly("org.jmonkeyengine:jme3-desktop:3.3.2-stable")
	runtimeOnly("org.jmonkeyengine:jme3-lwjgl:3.3.2-stable")
	runtimeOnly("org.jmonkeyengine:jme3-niftygui:3.3.2-stable")

}

application {
    mainClass.set("hotlinecesena.App")
}

tasks.test {
    useJUnitPlatform()
}
